services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server
    hostname: clickhouse-server
    ports:
      - "127.0.0.1:8123:8123"   # HTTP interface - bind to IPv4 localhost
      - "127.0.0.1:9000:9000"   # Native interface - bind to IPv4 localhost
    volumes:
      - ./config:/etc/clickhouse-server/config.d  # Mount custom config
      - ./users:/etc/clickhouse-server/users.d    # Mount user settings
      - ../data/clickhouse:/var/lib/clickhouse    # Persistent data volume
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
    networks:
      - iceberg_net
    restart: unless-stopped
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.19.2
    volumes:
      - ./migrations:/migrations
    environment:
      - GOOSE_DRIVER=clickhouse
      - GOOSE_DBSTRING=http://clickhouse:8123/
    networks:
      - iceberg_net
    restart: on-failure
    depends_on:
      clickhouse:
        condition: service_healthy

networks:
  iceberg_net:
    name: iceberg_network
    external: true
